Update farmer page translations for declension in Slavic languages
openchia/web pull request #240
Opened 2022-03-09 19:55 UTC by atomsymbol

A note about HTML syntax (not related to declension): The `<br>` tag doesn't require a slash. The `/` in `<br/>` is redundant in  HTML, however it is required in XHTML.

See also: https://en.wikipedia.org/wiki/Slovak_declension

2022-03-09 19:58 UTC, william-gr requested changes
Having tags within i18n makes translation harder, i think we need to find a better solution. Either removing the br tag or using css.

2022-03-09 20:42 UTC, atomsymbol commented
> Having tags within i18n makes translation harder, i think we need to find a better solution. Either removing the br tag or using css.

I have updated the code to use "white-space: pre-line" and newlines, instead of <br>.

2022-03-09 20:50 UTC, william-gr approved these changes
Thanks!

2022-03-09 20:50 UTC, merged

2022-03-10 03:23 UTC, atomsymbol commented
Unfortunately, the newline in "Failed Partials" didn't make it from `farmer.component.html` to http://translation.openchia.io nor to https://openchia.io/en/explorer/farmer/

It seems that it will be necessary to use `<br>`.